[workspace]
authors = ["Troy Smith <troy.smith@uga.edu>"]
channels = ["conda-forge"]
name = "CUDA-C-Final-Project"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.3,<3"
numpy = ">=2.3.3,<3"
matplotlib = ">=3.10.6,<4"
make = ">=4.4.1,<5"
gcc = ">=15.2.0,<15.3"
scipy = ">=1.16.2,<2"
pydantic = ">=2.12.3,<3"
